<?php


namespace App\Controllers;


use Core\Controller;
use Core\Router;

class RegistrationController extends Controller
{
    public function reg()
    {
        $this->render('Register'); // TODO: Change the autogenerated stub
    }
}